import Head from 'next/head'
import Welcome from '@/components/Welcome'
import ScrollEffect from '@/components/ScrollEffect'
import AboutMe from '@/components/AboutMe'
import FloatMenu from '@/components/FloatMenu'
import Projects from '@/components/Projects'
import { useLang } from '@/hooks/useLang'
import Footer from '@/components/Footer'
import Contact from '@/components/Contact'
import { Box } from '@chakra-ui/react'
import Skills from '@/components/Skills'


export default function Home() {
  const { lang, toggleLang } = useLang()

  return (
    <>
      <Head>
        <title>Nicolas Muñoz - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Welcome />
        <ScrollEffect />
        <FloatMenu lang={lang} toggleLang={toggleLang} />
        <AboutMe lang={lang} />
        <Skills lang={lang} />
        <Projects lang={lang} />
        <Contact lang={lang}/>
        <Footer lang={lang} />
      </main>
    </>
  )
}
